name: spritz-wine-tkg-ntsync

on:
  schedule:
    - cron: '0 0 */7 * *'
  workflow_dispatch:
  push:
    tags:
      - 'ntsync-spritz*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.10.0
      with:
        driver: docker

    - name: Run build.sh script
      run: |
        chmod +x build.sh
        WINE_OSU="false" BUILD_NAME="spritz-wine" \
        USE_TKG="true" PATCHSET="remote:latest" \
        PATCHSET_REPO="https://github.com/NelloKudo/WineSpritz.git" \
        WINE_BRANCH="ntsync" TAG_FILTER="ntsync-spritz*" ./build.sh
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: spritz-wine-tkg-ntsync
        path: ./*.tar.xz
        
    - name: Release
      uses: softprops/action-gh-release@v2.2.1
      if: github.ref_type == 'tag'
      with:
        files: ./*.tar.xz
        release_name: "spritz-wine-tkg-${{ github.ref_name }}"
        make_latest: false
