name: wine-osu-winello-arm
on:
  workflow_dispatch:
  push:
    branches:
      - 'arm64'
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    name: Build Wine (ARM64)
    steps:
      - name: Debloat GitHub CI
        uses: endersonmenezes/free-disk-space@v2
        with:
          remove_android: true
          remove_dotnet: true
          remove_haskell: true
      - uses: actions/checkout@v4
      - name: Restore ccache
        id: ccache-restore
        uses: actions/cache/restore@v4
        with:
          path: ./ccache
          key: ccache-arm64-${{ github.run_id }}
          restore-keys: |
            ccache-arm64-
      - uses: docker/setup-buildx-action@v3.10.0
        with:
          driver: docker
      - name: Run build.sh
        run: |
          chmod +x build.sh
          ./build.sh "true" "true" "false" "true" "false"
      - name: Save ccache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: ./ccache
          key: ${{ steps.ccache-restore.outputs.cache-primary-key }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wine-osu-arm64
          path: ./*.tar.xz
